name: "Fifth Workflow"
on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Comments"
      run: echo "Building Application"
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: "comments"
      run: echo "Testing the build"
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - name: "comments"
      run: echo "Deplying the Application" 
