name: Second Flow 

on:
    push:

jobs:
    build:
        runs-on: ubuntu:latest
        steps:
            - name: "checkingout Repo"
              uses: actions/checkout@v4
            - run: |
                  echo "Code Downloaded"
            - name: "Build"
              run: |
                echo "Build Started"
            
